### ISSUE TITLE
Software License

### ISSUE THREAD

**Issue by riptl** [mparisi20/dolmatch#1]
Hey, this is an amazing tool! I was wondering if you are willing to release this code under a open source software license like BSD or GPLv3.

I was working on similar function identification tooling, but working with Wii MEM1 dumps instead of DOL files. I would love to use/port your existing work rather than re-invent stuff.

Thanks,
terorie

**Comment by mparisi20** [comment]
Hi terorie, 

Thanks! I've added an open source software license (MIT) to the project. I hope you find it useful.

-Max
